<!DOCTYPE html>
<html lang="en">
<head>
    <?php
    $head_title = "Cookies & Privacy Policy | CDN OUT";
    $description = "Cookies and Privacy Policies for CDNOUT";
    $base_url = "";
    include($base_url . 'meta/_head.php');
    ?>
</head>
<body class="page-default">
<div id="page">
    <?php  include($base_url.'meta/_header.php'); ?>
    <header class="page-head">
        <div class="img-bg"></div>
        <div class="container-large">
            <h1>Cookies & Privacy Policy</h1>
            <p>Last Updated: <time datetime="2022-04-26">26th Apr, 2022</time></p>
        </div>

    </header>
    <main>
        <div class="container-large content-detailed">
            <h2>Cookies & Privacy</h2>
            <p>CDNOUT.com <br>2020 - <?php echo date("Y"); ?> &copy; CDNOUT.COM All Rights Reserved.</p>
            <h2>Intoduction</h2>
            <p>Thank you for choosing to be part of our community at CDNOUT.com (“company”, “we”, “us”, or “our”). We are committed to protecting your personal information and your right to privacy. If you have any questions or concerns about our policy, or our practices with regards to your personal information, please contact us at info@cdnout.com.</p>
            <p>When you visit our website CDNOUT (“Site”) and use our services, you trust us with your personal information. We take your privacy very seriously. In this privacy notice, we describe our privacy policy. We seek to explain to you in the clearest way possible what information we collect, how we use it and what rights you have in relation to it. We hope you take some time to read through it carefully, as it is important. If there are any terms in this privacy policy that you do not agree with, please discontinue use of our site and our services.</p>
            <p>This privacy policy applies to all information collected through our websites (such as https://cdnout.com) ("Apps"), and/or any related services, sales, marketing or events (we refer to them collectively in this privacy policy as the "Sites").</p>
            <h2>About CDNOUT: </h2>
            <p>CDNOUT aim to help developers and make their life easier. We provide Live First CDN resources for Libraries, Plugins, frameworks or Custom Codes by using own hosting servers. We also provide information about 3rd party CDN URLs for Libraries, Plugins and Frameworks.</p>
            <p>We have added ZIP files to download directly at once for developers with ease. We also provide plugin/framework information including Git, NPM Commands and other details.</p>
            <h3>What is CDN?</h3>
            <p>A content delivery network (CDN) refers to a geographically distributed group of servers which work together to provide fast delivery of Internet content.</p>
            <p>A CDN allows for the quick transfer of assets needed for loading Internet content including HTML pages, javascript files, stylesheets, images, and videos. The popularity of CDN services continues to grow, and today the majority of web traffic is served through CDNs, including traffic from major sites like Facebook, Netflix, and Amazon.</p>
            <h2>Do we collect data for our website?</h2>
            <p>Currently we do not have Login/Sign information So we personally do not collect of your data including Emails, Passwords, phone numbers and others.</p>
            <p>We just collect EMAILs via our "Signup for Newsletter" widget/block for newsletter purpose only, we do not provide these emails to any third party services.</p>
            <p>We do not selling any product, however we recommend through our blog or any article through which we may earn some commisions.</p>
            <h2>Do we use third party applications to collect any of your data?</h2>
            <p>Yes, In order to control website traffic and website secrity we analze website traffic to analyze visitors details including browser, OS and other related information.</p>
            <h2>DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?</h2>
            <p>In Short: We may use cookies and other tracking technologies to collect and store your information.</p>
            <p>We may use cookies and similar tracking technologies (like web beacons and pixels) to access or store information.</p>
            <h3>What are cookies? </h3>
            <p>A cookie is a small amount of data generated by a website and saved by your web browser. Its purpose is to remember information about you, similar to a preference file created by a software application.</p>
            <h2>External links:</h2>
            <p>Our website may contain external links which refer to other websites/apps. It is not necessary and we are not responsible for any external website's privacy, cookies and otehr policies.</p>
            <h2>Third party Advertisers</h2>
            <p>Our website visitors should know that we may place third party ads such as "Google AdSense" on our website ("www.cdnout.com") which maybe using site cookies and user/device information to serve best and personalized results. </p>
            <h4>About Google Adsense</h4>
            <p>Google uses cookies to help serve the ads it displays on the websites of its partners, such as websites displaying Google ads or participating in Google certified ad networks. When users visit a Google partner's website, a cookie may be dropped on that end user's browser.</p>
            <p>Third party vendors, including Google, use cookies to serve ads based on a user's prior visits to your website or other websites.</p>
            <p>Google's use of advertising cookies enables it and its partners to serve ads to your users based on their visit to your sites and/or other sites on the Internet.</p>
            <p>Users may opt out of personalized advertising by visiting Ads Settings. (Alternatively, you can direct users to opt out of a third-party vendor's use of cookies for personalized advertising by visiting www.aboutads.info.)</p>
            <h2>Disclaimer</h2>
            <p>Disclaimer: Information collected from different top relevant websites. It is tried to keep the information correct. </p>
            <h2>How you may contact us?</h2>
            <p> If you find anything wrong email us <a href="mailto:info@cdnout.com">info@cdnout.com</a></p>
        </div>
    </main>
</div>
<?php include($base_url . 'meta/_footer.php'); ?>

</body>
</html>