/**
 * @license
 * v1.3.11
 * MIT (https://github.com/pnp/pnpjs/blob/master/LICENSE)
 * Copyright (c) 2020 Microsoft
 * docs: https://pnp.github.io/pnpjs/
 * source: https://github.com/pnp/pnpjs
 * bugs: https://github.com/pnp/pnpjs/issues
 */
!function(e,t){"object"==typeof exports&&"undefined"!=typeof module?t(exports,require("@pnp/common"),require("@pnp/sp")):"function"==typeof define&&define.amd?define(["exports","@pnp/common","@pnp/sp"],t):t((e.pnp=e.pnp||{},e.pnp["sp-addinhelpers"]={}),e.pnp.common,e.pnp.sp)}(this,function(e,p,r){"use strict";var t=(o.prototype.fetch=function(o,n){var s=this;if(void 0===SP||void 0===SP.RequestExecutor)throw Error("SP.RequestExecutor is undefined. Load the SP.RequestExecutor.js library (/_layouts/15/SP.RequestExecutor.js) before loading the PnP JS Core library.");var e,t,r=o.substring(0,o.indexOf("/_api")),i=new SP.RequestExecutor(r),u={};if(n.headers&&n.headers instanceof Headers)for(t=(e=n.headers.entries()).next();!t.done;)u[t.value[0]]=t.value[1],t=e.next();else u=n.headers;return new Promise(function(t,r){var e={error:function(e){r(s.convertToResponse(e))},headers:u,method:n.method,success:function(e){t(s.convertToResponse(e))},url:o};e=n.body?p.extend(e,{body:n.body}):p.extend(e,{binaryStringRequestBody:!0}),i.executeAsync(e)})},o);function o(){this.convertToResponse=function(e){var t=new Headers;if(void 0!==e.headers)for(var r in e.headers)e.headers[r]&&t.append(r,e.headers[r]);var o=204===e.statusCode?null:e.body;return new Response(o,{headers:t,status:e.statusCode,statusText:e.statusText})}}var n=function(e,t){return(n=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,t){e.__proto__=t}||function(e,t){for(var r in t)t.hasOwnProperty(r)&&(e[r]=t[r])})(e,t)};var s,i,u,a=(s=r.SPRest,n(i=d,u=s),i.prototype=null===u?Object.create(u):(c.prototype=u.prototype,new c),d.prototype.crossDomainSite=function(e,t){return this._cdImpl(r.Site,e,t,"site")},d.prototype.crossDomainWeb=function(e,t){return this._cdImpl(r.Web,e,t,"web")},d.prototype._cdImpl=function(e,t,r,o){if(!p.isUrlAbsolute(t))throw Error("The addInWebUrl parameter must be an absolute url.");if(!p.isUrlAbsolute(r))throw Error("The hostWebUrl parameter must be an absolute url.");var n=new e(p.combine(t,"_api/SP.AppContextSite(@target)"),o);return n.query.set("@target","'"+encodeURIComponent(r)+"'"),n.configure(this._options)},d);function c(){this.constructor=i}function d(){return null!==s&&s.apply(this,arguments)||this}var f=new a;e.SPRequestExecutorClient=t,e.SPRestAddIn=a,e.sp=f,Object.defineProperty(e,"__esModule",{value:!0})});
//# sourceMappingURL=sp-addinhelpers.es5.umd.min.js.map
