/**
 * @license
 * v1.3.11
 * MIT (https://github.com/pnp/pnpjs/blob/master/LICENSE)
 * Copyright (c) 2020 Microsoft
 * docs: https://pnp.github.io/pnpjs/
 * source: https://github.com/pnp/pnpjs
 * bugs: https://github.com/pnp/pnpjs/issues
 */
!function(t,e){"object"==typeof exports&&"undefined"!=typeof module?e(exports,require("@pnp/common")):"function"==typeof define&&define.amd?define(["exports","@pnp/common"],e):e((t.pnp=t.pnp||{},t.pnp["config-store"]={}),t.pnp.common)}(this,function(t,o){"use strict";var e=(i.prototype.add=function(t,e){this._settings.set(t,e)},i.prototype.addJSON=function(t,e){this._settings.set(t,o.jsS(e))},i.prototype.apply=function(i){var n=this;return new Promise(function(t,e){try{n._settings=o.mergeMaps(n._settings,o.objectToMap(i)),t()}catch(t){e(t)}})},i.prototype.load=function(i){var n=this;return new Promise(function(e,t){i.getConfiguration().then(function(t){n._settings=o.mergeMaps(n._settings,o.objectToMap(t)),e()}).catch(t)})},i.prototype.get=function(t){return this._settings.get(t)||null},i.prototype.getJSON=function(t){var e=this.get(t);return null==e?e:JSON.parse(e)},i);function i(t){void 0===t&&(t=new Map),this._settings=t}var n=(r.prototype.getWrappedProvider=function(){return this.wrappedProvider},r.prototype.getConfiguration=function(){var e=this;return this.store&&this.store.enabled?this.store.getOrPut(this.cacheKey,function(){return e.wrappedProvider.getConfiguration().then(function(t){return e.store.put(e.cacheKey,t),t})}):this.wrappedProvider.getConfiguration()},r.prototype.selectPnPCache=function(){var t=new o.PnPClientStorage;if(t.local&&t.local.enabled)return t.local;if(t.session&&t.session.enabled)return t.session;throw Error("Cannot create a caching configuration provider since cache is not available.")},r);function r(t,e,i){this.wrappedProvider=t,this.cacheKey=e,this.wrappedProvider=t,this.store=i||this.selectPnPCache()}var s=(a.prototype.getConfiguration=function(){var i=this;return this.web.lists.getByTitle(this.listTitle).items.select(this.keyFieldName,this.valueFieldName).get().then(function(t){return t.reduce(function(t,e){return t[e[i.keyFieldName]]=e[i.valueFieldName],t},{})})},a.prototype.asCaching=function(t){return void 0===t&&(t="pnp_configcache_splist_"+this.web.toUrl()+"+"+this.listTitle),new n(this,t)},a);function a(t,e,i,n){void 0===e&&(e="config"),void 0===i&&(i="Title"),void 0===n&&(n="Value"),this.web=t,this.listTitle=e,this.keyFieldName=i,this.valueFieldName=n}t.Settings=e,t.CachingConfigurationProvider=n,t.SPListConfigurationProvider=s,Object.defineProperty(t,"__esModule",{value:!0})});
//# sourceMappingURL=config-store.es5.umd.min.js.map
